version: "3.8"

services:
  admes_application:
    restart: unless-stopped
    build: .
    container_name: admes_backend
    expose:
      - 7777
    networks:
      - server

networks:
  server:
    external: true